// src/data/data.js

export const companies = [
    {id:1, name: "UnBounce", image: "/assets/asset-3.png" },
    {id:2, name: "HubSpot", image: "/assets/asset-4.png" },
    {id:3, name: "Slack", image: "/assets/asset-5.png" },
    {id:4, name: "Dropbox", image: "/assets/asset-6.png" },
    {id:5, name: "Asana", image: "/assets/asset-7.png" },
    {id:6, name: "Trello", image: "/assets/asset-8.png" },
    {id:7, name: "Zoom", image: "/assets/asset-9.png" },
    {id:8, name: "Spotify", image: "/assets/asset-10.png" },
    {id:9, name: "Netflix", image: "/assets/asset-11.png" },
    {id:10, name: "Airbnb", image: "/assets/asset-12.png" },
    {id:11, name: "Canva", image: "/assets/asset-13.png" },
    {id:12, name: "Figma", image: "/assets/asset-14.png" },
    {id:13, name: "Amazon", image: "/assets/asset-15.png" },
    {id:14, name: "Google", image: "/assets/asset-16.png" },
    {id:15, name: "Microsoft", image: "/assets/asset-17.png" },
    {id:16, name: "Facebook", image: "/assets/asset-18.png" },
    {id:17, name: "Instagram", image: "/assets/asset-19.png" },
    {id:18, name: "Twitter", image: "/assets/asset-20.png" },
    {id:19, name: "LinkedIn", image: "/assets/asset-21.png" },
    {id:20, name: "Pinterest", image: "/assets/asset-22.png" },
    {id:21, name: "GitHub", image: "/assets/asset-24.png" },
    {id:22, name: "Bitbucket", image: "/assets/asset-25.png" },
    {id:23, name: "YouTube", image: "/assets/asset-23.png" },
    {id:24, name: "Atlassian", image: "/assets/asset-26.png" },
    {id:25, name: "Shopify", image: "/assets/asset-27.png" },
    {id:26, name: "Stripe", image: "/assets/asset-28.png" },
    {id:27, name: "PayPal", image: "/assets/asset-29.png" },
    {id:28, name: "Tesla", image: "/assets/asset-4.png" },
    {id:29, name: "SpaceX", image: "/assets/asset-8.png" },
    {id:30, name: "Adobe", image: "/assets/asset-32.png" },
    {id:31, name: "Oracle", image: "/assets/asset-10.png" },
    {id:32, name: "Salesforce", image: "/assets/asset-34.png" },
    {id:33, name: "ZoomInfo", image: "/assets/asset-35.png" },
    {id:34, name: "Zendesk", image: "/assets/asset-36.png" },
    {id:35, name: "Mailchimp", image: "/assets/asset-51.png" },
    {id:36, name: "Squarespace", image: "/assets/asset-20.png" },
  ];
  